AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template to deploy Management Console Private Access   
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Select VPC, Subnet and Security Group
        Parameters:
          - vpcId
          - subnet1
          - subnet2
          - sgForEndpoint

Parameters:
  vpcId:
    Type: AWS::EC2::VPC::Id
    Description: Choose VPC to deploy the console and signin VPC Endpoints
  subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Choose a private subnet in first Availability Zone
  subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Choose a private subnet in a second Availability Zone
  sgForEndpoint:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for the Console, Signin endpoints and Inbound Resolver endpoint


Resources:
    consoleEndpoint:
        Type: AWS::EC2::VPCEndpoint
        Properties: 
          PrivateDnsEnabled: false
          ServiceName: 'com.amazonaws.us-east-1.console'
          SubnetIds: 
            - !Ref subnet1
            - !Ref subnet2
          SecurityGroupIds:
            - !Ref sgForEndpoint
          VpcEndpointType: Interface
          VpcId: !Ref vpcId
          
          
    signinEndpoint:
        Type: AWS::EC2::VPCEndpoint
        Properties: 
          PrivateDnsEnabled: false
          ServiceName: 'com.amazonaws.us-east-1.signin'
          SubnetIds: 
            - !Ref subnet1
            - !Ref subnet2
          SecurityGroupIds:
            - !Ref sgForEndpoint
          VpcEndpointType: Interface
          VpcId: !Ref vpcId

    inboundResolver:
        Type : AWS::Route53Resolver::ResolverEndpoint
        Properties :
          Direction : Inbound
          IpAddresses : 
            - SubnetId: !Ref subnet1
            - SubnetId: !Ref subnet2
          Name : InboundEndpoint
          SecurityGroupIds : 
            - !Ref sgForEndpoint
    hostedZone: 
      Type: "AWS::Route53::HostedZone"
      Properties: 
        HostedZoneConfig: 
          Comment: 'Private zone for aws.amazon.com'
        Name: 'aws.amazon.com'
        VPCs: 
          - 
            VPCId: !Ref vpcId
            VPCRegion: 'us-east-1'

    consoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: console.aws.amazon.com
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]

    globalconsoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: global.console.aws.amazon.com
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]

    supportconsoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: support.console.aws.amazon.com
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]

    use1consoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: us-east-1.console.aws.amazon.com
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]

    widgetconsoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: "*.widget.console.aws.amazon.com"
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]

    nmconsoleRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt consoleEndpoint.DnsEntries]]]
          Name: networkmanager.console.aws.amazon.com
          Type: A
        DependsOn: [consoleEndpoint, hostedZone]


    signinRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt signinEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt signinEndpoint.DnsEntries]]]
          Name: signin.aws.amazon.com
          Type: A
        DependsOn: [signinEndpoint, hostedZone]
        
    use1signinRecord:
        Type: AWS::Route53::RecordSet
        Properties:
          HostedZoneId : !GetAtt hostedZone.Id
          AliasTarget:
            DNSName: !Select ['1', !Split [':', !Select ['0', !GetAtt signinEndpoint.DnsEntries]]]
            HostedZoneId: !Select ['0', !Split [':', !Select ['0', !GetAtt signinEndpoint.DnsEntries]]]
          Name: us-east-1.signin.aws.amazon.com
          Type: A
        DependsOn: [signinEndpoint, hostedZone]

Outputs:
  ConsoleVpcEndpointId:
    Description: Console VPC Endpoint Id
    Value: !GetAtt consoleEndpoint.Id
  SigninVpcEndpointId:
    Description: Signin VPC Endpoint Id
    Value: !GetAtt signinEndpoint.Id    
  InboundResolverEndpointId:
    Description: Signin VPC Endpoint Id
    Value: !GetAtt inboundResolver.ResolverEndpointId   

  
